---
title: "Chapter 3: Chroma features"
order: 3
---

Chromagrams of all four songs, structured in per song, per side, total. So first a song and analyses, then of the other from that side, then comparing those. Then the other side and concluding what we see in total


```{r setup}
#| echo: false
#| warning: false
#| message: false
source("../visualisation_funcs.R")
```

#### Listen to Give me the Loot and Bitch Plase
<audio controls style="width: 100%;">
  <source src="../gmtl.m4a" type="audio/mp4">
</audio>

<audio controls style="width: 100%;">
  <source src="../bp.m4a" type="audio/mp4">
</audio>

```{r, fig.width=11, fig.height=6}
#| echo: false
#| warning: false
#| message: false
most_east <- gen_chromagram("../data_sv/chromagram_gmtl.csv", "chebyshev", "Give Me The Loot", "The Notorius B.I.G")
most_west <- gen_chromagram("../data_sv/chromagram_bp.csv", "chebyshev", "Bitch Please", "Snoop Dogg & Xzibit")

grid_plot <- (most_east | most_west)

final_plot_cg <- grid_plot + 
  plot_layout(
    guides = "collect"     # Forces a single legend for the whole patch
  ) + 
  plot_annotation(
    title = "Comparison of Chroma features for Most typical E.C. and W.C. track"
  )&
  scale_fill_viridis_c()
  final_plot_cg

ssm_east <- gen_ssm_chroma("../data_sv/chromagram_gmtl.csv", "euclidean", "Give Me The Loot", "The Notorius B.I.G")
ssm_west <- gen_ssm_chroma("../data_sv/chromagram_bp.csv", "euclidean", "Bitch Please", "Snoop Dogg & Xzibit")


grid_plot <- (ssm_east | ssm_west)

final_plot_ssm <- grid_plot + 
  plot_layout(
    guides = "collect"     # Forces a single legend for the whole patch
  ) + 
  plot_annotation(
    title = "Comparison of Chroma SSM for Most typical E.C. and W.C. track"
  )&
  scale_fill_viridis_c()
  final_plot_ssm
```

#### Listen to C.R.E.A.M and Without Me
<audio controls style="width: 100%;">
  <source src="../cream.m4a" type="audio/mp4">
</audio>

<audio controls style="width: 100%;">
  <source src="../wm.m4a" type="audio/mp4">
</audio>

```{r, fig.width=11, fig.height=6}
#| echo: false
#| warning: false
#| message: false
most_east <- gen_chromagram("../data_sv/chromagram_cream.csv", "chebyshev", "C.R.E.A.M", "Wu-Tang Clan")
most_west <- gen_chromagram("../data_sv/chromagram_wm.csv", "chebyshev", "Without Me", "Eminem")

grid_plot <- (most_east | most_west)

final_plot_cg <- grid_plot + 
  plot_layout(
    guides = "collect"     # Forces a single legend for the whole patch
  ) + 
  plot_annotation(
    title = "Comparison of Chroma features for Most distinct E.C. and W.C. track"
  )&
  scale_fill_viridis_c()
  final_plot_cg

ssm_east <- gen_ssm_chroma("../data_sv/chromagram_cream.csv", "euclidean", "C.R.E.A.M", "Wu-Tang Clan")
ssm_west <- gen_ssm_chroma("../data_sv/chromagram_wm.csv", "euclidean", "Without Me", "Eminem")


grid_plot <- (ssm_east | ssm_west)

final_plot_ssm <- grid_plot + 
  plot_layout(
    guides = "collect"     # Forces a single legend for the whole patch
  ) + 
  plot_annotation(
    title = "Comparison of Chroma SSM for Most distinct E.C. and W.C. track"
  ) &
  scale_fill_viridis_c()
  final_plot_ssm
```
