---
title: "Portfolio Overview"
order: 1
---

During the early to mid-1990s, the American hip-hop landscape was defined by an intense and highly publicized rivalry between the East Coast and the West Coast. Rooted in regional pride and fueled by competing record labels, the feud grew from a musical competition into a severe cultural conflict. The central figures of this divide were The Notorious B.I.G. (representing the East Coast) and Tupac Shakur (representing the West Coast).

What began as lyrical jabs and media provocation eventually escalated into real-world violence. This era of hip-hop was marked by an underlying tension that tragically culminated in the drive-by shootings and unsolved murders of Shakur in September 1996 and The Notorious B.I.G. just six months later in March 1997.

While the history, the media coverage, and the cultural tragedy of this era are heavily documented, this portfolio tries to answers the question whether this east-west feud was not only prevalent in culture, but also whether there was a real difference in the music itself.

First, we take a look at the corpus and the main spread of it's features. Then, we dive deeper into four songs from the corpus, by looking at Chroma, Timbre, Tempo and loudness. After that, we will try to cluster and classify the songs, looking at whether machine learning models can seperate the coasts.